import 'dart:convert';
import 'dart:io';

// Generate the SQL snapshot from the same structured catalog shipped offline.
void main() {
  final catalog =
      jsonDecode(File('assets/exercises/catalog.json').readAsStringSync())
          as Map<String, dynamic>;
  final rows = catalog['exercises'] as List;
  final literal = jsonEncode(rows).replaceAll("'", "''");
  final output = File('supabase/seeds/exercises.sql');
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(
    '''-- Generated by dart run tool/export_exercise_seed.dart. Review before applying.
insert into public.exercises (
  id, name, muscle_group, type, aliases, description, primary_muscle,
  secondary_muscles, equipment, difficulty, instructions, common_errors,
  safety_tips, alternatives, media, is_active
)
select
  row->>'id', row->>'name', row->>'muscle_group', row->>'type',
  coalesce(row->'aliases', '[]'::jsonb), coalesce(row->>'description', ''),
  coalesce(row->>'primary_muscle', ''), coalesce(row->'secondary_muscles', '[]'::jsonb),
  coalesce(row->'equipment', '[]'::jsonb), coalesce(row->>'difficulty', 'unspecified'),
  coalesce(row->'instructions', '[]'::jsonb), coalesce(row->'common_errors', '[]'::jsonb),
  coalesce(row->'safety_tips', '[]'::jsonb), coalesce(row->'alternatives', '[]'::jsonb),
  nullif(row->'media', 'null'::jsonb), coalesce((row->>'is_active')::boolean, true)
from jsonb_array_elements('$literal'::jsonb) as catalog(row)
on conflict (id) do nothing;
-- Existing curated server content is intentionally not overwritten by this seed.
''',
  );
}
